# Generated by Django 4.2.30 on 2026-08-26 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('genero', models.CharField(choices=[('ACCION', 'Acción'), ('COMEDIA', 'Comedia'), ('DRAMA', 'Drama'), ('TERROR', 'Terror'), ('CIENCIA_FICCION', 'Ciencia ficción'), ('ANIMACION', 'Animación'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('anio_estreno', models.PositiveIntegerField()),
                ('duracion_minutos', models.PositiveIntegerField()),
                ('sinopsis', models.TextField(blank=True)),
                ('calificacion', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peliculas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
